title: Duckduki
description: Assistente Desktop Inteligente com IA Generativa
baseurl: ""
url: "https://jdalmeida.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - node_modules/
  - package.json
  - package-lock.json

include:
  - _headers 
